"""empty message

Revision ID: a558d8b83486
Revises: 626e853a26c5
Create Date: 2024-12-05 15:53:51.557190

"""
from typing import Sequence, Union

import sqlalchemy as sa

import src
from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'a558d8b83486'
down_revision: Union[str, None] = '626e853a26c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_feedback_about_client_id'), 'feedback_about_client', ['id'])
    op.create_unique_constraint(op.f('uq_legal_entity_id'), 'legal_entity', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_legal_entity_id'), 'legal_entity', type_='unique')
    op.drop_constraint(op.f('uq_feedback_about_client_id'), 'feedback_about_client', type_='unique')
    # ### end Alembic commands ###